### ISSUE TITLE
Steps Information

### ISSUE THREAD

**Issue by aubombarely** [LongTianPy/WGD#3]
The pipeline runs over different steps. It will informative for the user if while the pipeline is running, it get messages like:

\====================
SkewGB pipeline starts
Date XXXXXXXX
\====================

Step 1 of Z: Translating CDS to proteins start (date)
XXXXXX CDS have been translated to proteins

Step 2 of Z: Building the selfblast database (date)

Step 3 of Z: Performing selfblast (date)
XXXXX hits were detected excluding selfhits.

....

**Comment by LongTianPy** [comment]
Solved.
