### ISSUE TITLE
Failed test run with A. thaliana 

### ISSUE THREAD

**Issue by aubombarely** [LongTianPy/WGD#5]
aurebg@begonia:/data/aurebg_projects/WGD$ python /data/software/SkewGD/WGD_detection.py -i Athaliana_Phytozome167_TAIR10.cds.fa -o WGD_Atha/Atha_MCL -d WGD_Atha/ -y /usr/local/bin/yn00 

*\* (WGD_detection.py:10372): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-Cf5K2FmXPG: Connection refused
Translating CDS to proteins...

/usr/local/lib/python2.7/dist-packages/Bio/Seq.py:2041: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
Self-blasting, this may take long...

Building a new DB, current time: 05/06/2016 16:25:21
New DB name:   /data/aurebg_projects/WGD/Athaliana_Phytozome167_TAIR10.cds.fa.protein
New DB title:  Athaliana_Phytozome167_TAIR10.cds.fa.protein
Sequence type: Protein
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 27416 sequences in 1.65178 seconds.
Clustering...
..[mcl] new tab created
[mcl] pid 19353
 ite -------------------  chaos  time hom(avg,lo,hi) expa expb expc fmv
  1  ...................  30.09  0.08 1.02/0.02/3.66 2.17 2.17 2.17   0
  2  ...................  47.06  0.18 0.90/0.19/1.55 2.34 1.35 2.94   7
  3  ...................  25.04  0.22 0.83/0.11/2.87 2.30 0.69 2.02  10
  4  ...................  17.66  0.12 0.82/0.17/3.61 1.93 0.69 1.40   6
  5  ...................  20.96  0.06 0.85/0.21/2.28 1.28 0.72 1.01   1
  6  ...................  10.83  0.04 0.88/0.20/2.51 1.06 0.74 0.74   0
  7  ...................   5.50  0.03 0.91/0.39/2.26 1.02 0.74 0.55   0
  8  ...................   2.18  0.02 0.94/0.46/1.36 1.01 0.75 0.41   0
  9  ...................   1.39  0.01 0.96/0.54/1.34 1.00 0.80 0.33   0
 10  ...................   0.95  0.01 0.98/0.52/1.19 1.00 0.86 0.28   0
 11  ...................   0.64  0.01 0.99/0.63/1.22 1.00 0.90 0.26   0
 12  ...................   0.48  0.01 0.99/0.58/1.00 1.00 0.94 0.24   0
 13  ...................   0.34  0.01 1.00/0.76/1.00 1.00 0.97 0.23   0
 14  ...................   0.25  0.01 1.00/0.76/1.00 1.00 0.98 0.23   0
 15  ...................   0.25  0.01 1.00/0.76/1.00 1.00 0.99 0.22   0
 16  ...................   0.24  0.01 1.00/0.76/1.00 1.00 0.99 0.22   0
 17  ...................   0.37  0.01 1.00/0.75/1.00 1.00 1.00 0.22   0
 18  ...................   0.50  0.01 1.00/0.63/1.00 1.00 1.00 0.22   0
 19  ...................   0.28  0.01 1.00/0.80/1.00 1.00 1.00 0.22   0
 20  ...................   0.03  0.01 1.00/0.97/1.00 1.00 1.00 0.22   0
 21  ...................   0.00  0.01 1.00/1.00/1.00 1.00 1.00 0.22   0
 22  ...................   0.00  0.01 1.00/1.00/1.00 1.00 1.00 0.22   0
[mcl] jury pruning marks: <99,99,99>, out of 100
[mcl] jury pruning synopsis: <99.0 or perfect> (cf -scheme, -do log)
[mcl] output is in Athaliana_Phytozome167_TAIR10.cds.fa.protein.mcl_out
[mcl] 5055 clusters found
[mcl] output is in Athaliana_Phytozome167_TAIR10.cds.fa.protein.mcl_out

Please cite:
    Stijn van Dongen, Graph Clustering by Flow Simulation.  PhD thesis,
    University of Utrecht, May 2000.
       (  http://www.library.uu.nl/digiarchief/dip/diss/1895620/full.pdf
       or  http://micans.org/mcl/lit/svdthesis.pdf.gz)
OR
    Stijn van Dongen, A cluster algorithm for graphs. Technical
    Report INS-R0010, National Research Institute for Mathematics
    and Computer Science in the Netherlands, Amsterdam, May 2000.
       (  http://www.cwi.nl/ftp/CWIreports/INS/INS-R0010.ps.Z
       or  http://micans.org/mcl/lit/INS-R0010.ps.Z)

Matching clusters...
5049
Traceback (most recent call last):
  File "/data/software/SkewGD/WGD_detection.py", line 125, in <module>
    main()
  File "/data/software/SkewGD/WGD_detection.py", line 41, in main
    afa_file_list = Hong_wrapper(nucleotide_cds=nucleotide_cds, identity=identity, coverage=coverage, output_prefix=out_prefix,working_dir=working_dir)
  File "/data/software/SkewGD/WGD_detection.py", line 95, in Hong_wrapper
    process_cluster_all.process_cluster(mcl_out=mcl_out, protein_cds=protein_cds, output_prefix=output_prefix,working_dir=working_dir)
  File "/data/software/SkewGD/process_cluster_all.py", line 41, in process_cluster
    with open(output_prefix+str(i)+'.txt','w') as output:
IOError: [Errno 2] No such file or directory: 'WGD_Atha/Atha_MCL1.txt'

**Comment by LongTianPy** [comment]
Could you try `python /data/software/SkewGD/WGD_detection.py -i Athaliana_Phytozome167_TAIR10.cds.fa -o Atha_MCL -d WGD_Atha/ -y /usr/local/bin/yn00`, please?
I don't think directory needs to be included in the output prefix parameter.

**Comment by aubombarely** [comment]
Hi Long, 

  I did it and it run ok.

  Thanks

  Best

  AUre

**Comment by LongTianPy** [comment]
No problem :)
